version: "3"

services:
  db:
    container_name: zespolowy_db
    image: mongo:latest
    restart: always
    environment:
      MONGODB_DATABASE: projekt-zespolowy-mongo
    volumes:
      - db:/var/lib/mongo:/data/db

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      MONGO_HOST: zespolowy_db
      MONGO_PORT: 27017
      MONGO_DATABASE: projekt-zespolowy-mongo
      APP_PORT: 5000
      APP_HOST: localhost
      APP_ADMIN_USERNAME: admin
      APP_ADMIN_EMAIL: ServiceAdminEmail@example.com
      APP_ADMIN_PASSWORD: Guest123!
      SECRET_KEY: guest
      ISSUER: kkolodziejski
      APP_PATH: /usr/src/app
    ports:
      - 5000:5000
    links:
      - db
    depends_on:
      - db
    volumes_from:
      - frontend

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      SERVER_URL: http://localhost:5000
      WEBSOCKET_URL: ws://localhost:5000
      ISSUER: kkolodziejski
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./frontend/.env
volumes:
  db:
    driver: local
